### PR TITLE
seq: add support for sequencing existing transforms

### LINKED ISSUE #14: Append one transform chain to another (concat chains)
If you have two existing transform objects, it would be great if you could append one to another after constructing. This is required for better transform reuse.

Example (zoom with a center point):
```javascript
import d3Transform from 'd3-transform';

const zoomTransform = d3Transform().scale(1.5);

// The 'x' and 'y' are calculated from the bounding box.
const originForwardTransform= d3Transform().translate([ x, y ]);
const originBackwardTransform= d3Transform().translate([ -x, -y ]);

// Notice the order.
const zoomCenteredTransform = d3Transform()
  .concat(originForwardTransform)
  .concat(zoomTransform)
  .concat(originBackwardTransform);
```

### PR DESCRIPTION
**Pull request by seliopou**
```javascript
var shift   = d3Transform.translate([x, y]),
    unshift = d3Transform.translate([-x, -y]);

shift.seq(unshift) /* identity (if the floats work out) */
```
I'll change the operation name (`seq` currently) to whatever the consensus name is.

Closes #14

### CODE REVIEW

**Comment by sompylasar** [comment]
@seliopou Great, thanks! Maybe add a readme item for this into the `Componsition` section, too.

**Comment by seliopou** [comment]
@sompylasar Done.

@trinary, have a look and see what you think. It's my opinion that it's worthwhile having something like this in the library.

**Comment by trinary** [comment]
Agreed. I think there's another tweak to make when it comes to sequenced functions, though:
```javascript
var t1 = d3Transform().translate(function(d) { return [d,1]; });
var t2 = d3Transform().translate(function(d) { return [1,d]; });
var seq = t1.seq(t2);

seq(5) => "translate(5,1) translate(1,)"
```
I started to write some simple tests and ran into that. :)

**Comment by trinary** [comment]
@seliopou I haven't taken a second look on this yet, did you want me to dig in?

**Comment by seliopou** [comment]
Ugh, sorry been distracted with other things. Wanna have a look?

**Comment by trinary** [comment]
I have this working with a couple tests on https://github.com/trinary/d3-transform/tree/seliopou-master, take a look @seliopou . I think we just need to deal with the evaluated seq the same as a chain. Sorry it took so long to work on this. :) If that change looks ok you can pull it back on this branch and merge, I can update npm/bower whenever after that.

**Pull request merged**
